[project]
name = "kai-llm"
version = "0.1.0"
description = "Large language model module for K.ai system (part of Kaspar 2028)"
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
  "kai-shared",
  "uvloop>=0.22.1",
  "vllm[audio]",
]

[tool.uv]
# prerelease = "if-necessary-or-explicit"
prerelease = "allow"
environments = [
  "sys_platform == 'linux'",
]

[tool.uv.sources]
kai-shared = { path = "./kai-shared", editable = true }
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[dependency-groups]
dev = [
    "ruff>=0.16.2",
    "ty>=0.0.70",
]
